spring:
  datasource:
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petshop?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
